# @format

captainVersion: 4
services:
  $$cap_appname-db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: $$cap_db_name
      MYSQL_USER: $$cap_db_user
      MYSQL_PASSWORD: $$cap_db_pass
      MYSQL_DATABASE: $$cap_db_name
    restart: always
    volumes:
      - /filerun/db:/var/lib/mysql
  $$cap_appname:
    image: filerun/filerun:arm64v8
    volumes:
      - $$cap_appname-html:/var/www/html
      - $$cap_appname-userfiles:/user-files
    restart: always
    depends_on:
      - $$cap_appname-db
    environment:
      FR_DB_HOST: $$cap_appname-db
      FR_DB_PORT: 3306
      FR_DB_NAME: $$cap_db_name
      FR_DB_USER: $$cap_db_user
      FR_DB_PASS: $$cap_db_pass
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
caproverOneClickApp:
  variables:
    - description: Database name
      defaultValue: filerun
      id: $$cap_db_name
      label: DB Name
    - id: $$cap_db_user
      label: Database user
      defaultValue: filerunuser
    - id: $$cap_db_pass
      label: Database password
      description: ""
      validRegex: /.{1,}/

  instructions:
    start: >-
      FileRun is a self-hosted Google Drive alternative. It is a full featured web based file manager with an easy to use user interface. It is great for managing your photo, movie, audio collection, or sharing files with your family and friends.

      Enter your Database Configuration parameters and click on next. A FileRun container will be created for you. The process will take about a minute for the process to finish. 

      Note: This app is intended for advanced users who'd like to have a central DB in a single container. You should start by configuring your DB first and then comeback with all the DB Information.
    end: >-
      FileRun is deployed and available as $$cap_appname-wordpress. 

      Username: superuser  Password: superuser

      IMPORTANT: It will take up to 2 minutes for FileRun to be ready. Before that, you might see a 502 error page.

      Remember that this app will not create a Database by itself. You need to provide all that information.
  displayName: FileRun - No DB (ARM)
  isOfficial: false
  description: FileRun is a self-hosted Google Drive alternative. It is a full featured web based file manager with an easy to use user interface.
  documentation: Taken from https://hub.docker.com/r/afian/filerun/.
